site_name: 'ijtdev/docs'
site_author: itsjusttriz
site_description: 'Documentation for all projects under the @ijtdev namespace'
site_url: https://docs.itsjusttriz.com/
theme:
    name: material
    custom_dir: overrides
    favicon: assets/image/favicon.png
    logo: assets/image/favicon.png
    palette:
        scheme: slate
        primary: custom
    features:
        - navigation.sections
        - navigation.indexes
        - navigation.path
        # - toc.integrate
nav:
    - Home: index.md
    - Documentation:
          - ijtdev/api:
                - projects/ijtdev-api/index.md
    - Changelog:
          - ijtdev/api: changelog/ijtdev-api.md

copyright: Copyright &copy; 2024 ItsJustTriz

extra:
    generator: false
    social:
        - icon: fontawesome/brands/discord
          link: http://discord.itsjusttriz.com
extra_css:
    - assets/stylesheets/extra.css
markdown_extensions:
    - attr_list
    - md_in_html
    - toc:
          toc_depth: 3
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
    - search
